### ISSUE TITLE
Rename bblfsh/dashboard to bblfsh/web

### ISSUE THREAD

**Issue by smola** [bblfsh/web#149]
- [x] Change repository name.
- [x] Update repo description and tags.
- [x] Travis CI synced
- [x] Update README/CONTRIBUTING
- [x] Rename binary [`bblfsh-dashboard`](https://github.com/bblfsh/dashboard/tree/master/server/cmd/) -> `bblfsh-web` 
- [ ] Check links from documentation of other projects.
- [x] Create bblfsh/web on Docker Hub.
- [x] Pushed older images to bblfsh/web.
- [x] Cut a release \w changelog, that would push bblfsh/web images to Docker Hub.
- [x] Update bblfsh/dashboard description on Docker Hub to point to bblfsh/web.
- [x] Coordinate update of the deployment [src-d/charts/bblfsh-dashboard](https://github.com/src-d/charts/tree/master/bblfsh-dashboard)

@bzz Before doing any of the changes, let's double check that the task list is comprehensive.

**Comment by bzz** [comment]
👍 Do you think it should also include update to https://github.com/src-d/charts/tree/master/bblfsh-dashboard ? \cc @rporres

**Comment by eiso** [comment]
Any need for name updates in our helm charts for the deployed version?

**Comment by bzz** [comment]
Comment above updated \w some questions

**Comment by rporres** [comment]
> do you think it should also include update to https://github.com/src-d/charts/tree/master/bblfsh-dashboard ? \cc @rporres

If there's a change in the name, it should also be reflected in the chart

> just to double-check: would this imply any changes in domain name for a public deployment of the http://dashboard.bblf.sh ?

I could set some time to move things to play.bblf.sh considering the whole change

**Comment by eiso** [comment]
Appreciate it @rporres, it's not time sensitive at all but would be nice to finalize that. I would just also request a 301 redirect from dashboard.bblf.sh to play.bblf.sh too since that link is widely shared.

**Comment by bzz** [comment]
Overall, looks great to me! Thank you @smola 

Marked it as umbrella, as would require at least 2 additional issues on top of administrative work:
 - one for binary rename and release
 - one for Infra and charts

**Comment by bzz** [comment]
Adding to the backlog.

@smola can help with all administrative parts of the rename

@smacker can you please help, taking care of other steps?

**Comment by smacker** [comment]
It's not clear for me how to update documentation.
Just replace `dashboard` by `web` would make it weird. 

> Web for [Babelfish server](https://bblf.sh).
> Babelfish server (v2.5.0 or newer) is required for web.
> When server starts web will be available on http://localhost:8080
> If don't want to run **web** using our *Docker* 

should we use something like `web interface` in documentation or `web playground` or ...?

**Comment by eiso** [comment]
`web client`

**Comment by bzz** [comment]
> somebody needs to update repo description and tags. I don't have access to do that.

Do not have access either, so @smola  please give us a ✋ 
Added to description

**Comment by bzz** [comment]
For links and documentation - it's https://docs.sourced.tech/intro/#getting-started-with-babelfish that needs to be updated as well as may be https://doc.bblf.sh/using-babelfish/getting-started.html#using-the-online-dashboard

**Comment by smacker** [comment]
I'm not sure where the source for that pages comes from. Maybe from docs repo? If so it's fixed already: https://github.com/bblfsh/documentation/pull/194

**Comment by smacker** [comment]
release:
https://github.com/bblfsh/web/releases/tag/v0.7.0
image pushed correctly:
https://hub.docker.com/r/bblfsh/web/tags/

**Comment by eiso** [comment]
Let's drop the word "Dashboard" from the top bar and let's replace the <title></title> to Babelfish Web. 

![2018-08-17-230221_439x176_scrot](https://user-images.githubusercontent.com/1247608/44290690-c8e11b00-a271-11e8-80d9-64507a8b1bc3.png)

**Comment by smacker** [comment]
Huh? Are you sure you run the last version?
<img width="431" alt="screen shot 2018-08-19 at 17 03 24" src="https://user-images.githubusercontent.com/406916/44310157-d9100c00-a3d1-11e8-8d2f-83ec9052b778.png">

**Comment by bzz** [comment]
@rporres are you going to take care of charts or shall a PR be submitted to src-d/charts by Apps as well?

**Comment by rporres** [comment]
@bzz As usual, if you need me to do anything please create an issue for it.

There are two tasks here: rename the chart and update terraform configuration. I definitely have to do the second part as you're not familiar with it. The chart renaming is up to you: you can send me a PR ([as you did with gitbase](https://github.com/src-d/charts/pull/65)) or you can create a rename-deployment issue

**Comment by bzz** [comment]
Sounds good!

@smacker can you please submit a PR to chart as well as it seems to be the last action item in here?

**Comment by smacker** [comment]
@bzz I'm not sure that rename wouldn't break anything. There is also should be a change of domain. I believe we should align it with @rporres instead of just making random changes.

**Comment by rporres** [comment]
@bzz the last action item will be to deploy the renamed chart. Please create an issue for that as well. Thx!

**Comment by bzz** [comment]
Change of the domain is not related to this changes and is tracked in the issue linked above.

I'm sure @rporres would be happy to review the chart changes, same as he did for @carlosms who took care of updating gitbase-web, but if in doubt please follow the advice above https://github.com/bblfsh/web/issues/149#issuecomment-414615044

**Comment by rporres** [comment]
I'm not talking about the domain here, @bzz. Since there's a chart name change, I will need to update the terraform configuration related to the change and that will trigger a new deployment.

I've created https://github.com/src-d/issues-infrastructure/issues/215 to take care of that.

**Comment by smacker** [comment]
pr to charts: https://github.com/src-d/charts/pull/67

**Comment by rporres** [comment]
> pr to charts: src-d/charts#67

Merged. Now it's on me to deploy it

**Comment by bzz** [comment]
For

>  Check links from documentation of other projects.

@eiso would the same logic be applicable here, as it https://github.com/src-d/gitbase-web/issues/218#issuecomment-414832903 ?

**Comment by eiso** [comment]
Yes
